//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class apc_annex_catgr
    {
        public apc_annex_catgr()
        {
            this.apc_annex_catgr_detail = new HashSet<apc_annex_catgr_detail>();
            this.employs = new HashSet<employ>();
            this.doc2_charge_poste = new HashSet<doc2_charge_poste>();
            this.lieu_nominaiton = new HashSet<lieu_nominaiton>();
        }
    
        public int id_apc_annex { get; set; }
        public string nom_apc_annex { get; set; }
    
        public virtual ICollection<apc_annex_catgr_detail> apc_annex_catgr_detail { get; set; }
        public virtual ICollection<employ> employs { get; set; }
        public virtual ICollection<doc2_charge_poste> doc2_charge_poste { get; set; }
        public virtual ICollection<lieu_nominaiton> lieu_nominaiton { get; set; }
    }
}
