//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class branche
    {
        public branche()
        {
            this.employ = new HashSet<employ>();
            this.rotba = new HashSet<rotba>();
        }
    
        public int id_branche { get; set; }
        public string nom_branche { get; set; }
        public string nom_corp { get; set; }
    
        public virtual ICollection<employ> employ { get; set; }
        public virtual ICollection<rotba> rotba { get; set; }
    }
}
