//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc2_charge_poste
    {
        public int id_charge { get; set; }
        public int n_9arar_charge { get; set; }
        public System.DateTime date_start_charge { get; set; }
        public Nullable<System.DateTime> date_fin_charge { get; set; }
        public int employ_id { get; set; }
        public int apc_annex_catgr_id_apc_annex { get; set; }
        public int apc_annex_catgr_detail_id_annex_detail { get; set; }
    
        public virtual employ employ { get; set; }
        public virtual apc_annex_catgr apc_annex_catgr { get; set; }
        public virtual apc_annex_catgr_detail apc_annex_catgr_detail { get; set; }
    }
}
