//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc2_chngmt_daraja
    {
        public int id_chngmnt_daraja { get; set; }
        public string period_daraja { get; set; }
        public int valeur_daraja { get; set; }
        public System.DateTime date_daraja { get; set; }
        public int employ_id { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
