//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc2_chngmnt_delgation
    {
        public int id_chngmnt_delegation { get; set; }
        public int n_delegation { get; set; }
        public System.DateTime date_start_delegation { get; set; }
        public Nullable<System.DateTime> date_fin_delegation { get; set; }
        public string type_delegation { get; set; }
        public int employ_id { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
