//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_displine
    {
        public int id_displine { get; set; }
        public string titre { get; set; }
        public int n_displine { get; set; }
        public string hokem_9adaii { get; set; }
        public System.DateTime date_7okem { get; set; }
        public System.DateTime date_arrete { get; set; }
        public int employ_id { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
