//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_morasalt_idariya
    {
        public int id_morasalt { get; set; }
        public string titre_morasala { get; set; }
        public int employ_id { get; set; }
        public int n_morasalt { get; set; }
        public System.DateTime date_morasalt { get; set; }
        public byte[] scan_doc_morsalt { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
