//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_mo7asaba
    {
        public int id_mo7asaba { get; set; }
        public int nbr_day_absence { get; set; }
        public System.DateTime date1_abs { get; set; }
        public System.DateTime date2_abs { get; set; }
        public int employ_id { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
