//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_ta9yim
    {
        public int id_ta9yom { get; set; }
        public string type_ta9yim { get; set; }
        public int employ_id { get; set; }
        public System.DateTime date_ta9yim { get; set; }
        public string ta9dir_annee { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
