//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_promotion
    {
        public int id_promtion { get; set; }
        public int n_promtion { get; set; }
        public System.DateTime date_promtion { get; set; }
        public int employ_id { get; set; }
        public int rotba_id_rotba { get; set; }
    
        public virtual employ employ { get; set; }
        public virtual rotba rotba { get; set; }
    }
}
