//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_vacane_plus
    {
        public int id_vac_plus { get; set; }
        public string titre_vacplus { get; set; }
        public System.DateTime date_out_vacpus { get; set; }
        public System.DateTime date_in_vacplus { get; set; }
        public int employ_id { get; set; }
        public int nbr_day_vac { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
