//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_vacance
    {
        public int id_vacnace { get; set; }
        public int vacance_year { get; set; }
        public int nbr_cons { get; set; }
        public int nbr_rest { get; set; }
        public System.DateTime date_vac_out { get; set; }
        public System.DateTime date_vac_in { get; set; }
        public string nom_interim { get; set; }
        public int employ_id { get; set; }
        public string place_vac { get; set; }
    
        public virtual employ employ { get; set; }
    }
}
