//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class employ
    {
        public employ()
        {
            this.doc_vacance = new HashSet<doc_vacance>();
            this.doc_promotion = new HashSet<doc_promotion>();
            this.doc_ta9yim = new HashSet<doc_ta9yim>();
            this.doc_displine = new HashSet<doc_displine>();
            this.doc_7araka = new HashSet<doc_7araka>();
            this.doc_vacane_plus = new HashSet<doc_vacane_plus>();
            this.doc_morasalt_idariya = new HashSet<doc_morasalt_idariya>();
            this.doc_mo7asaba = new HashSet<doc_mo7asaba>();
            this.doc2_chngmnt_poste = new HashSet<doc2_chngmnt_poste>();
            this.doc2_chngmt_daraja = new HashSet<doc2_chngmt_daraja>();
            this.doc2_chngmnt_delgation = new HashSet<doc2_chngmnt_delgation>();
            this.doc2_charge_poste = new HashSet<doc2_charge_poste>();
            this.lieu_nominaiton = new HashSet<lieu_nominaiton>();
        }
    
        public int id { get; set; }
        public string nom_ar { get; set; }
        public string prenom_ar { get; set; }
        public string nom_fr { get; set; }
        public string prenom_fr { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> date_n { get; set; }
        public string lieu_n { get; set; }
        public string adresse { get; set; }
        public byte[] photo { get; set; }
        public System.DateTime date_install { get; set; }
        public string rank_orgnl { get; set; }
        public string n_ccp { get; set; }
        public string n_cnas { get; set; }
        public string situation_fml { get; set; }
        public int id_vacance { get; set; }
        public string catgr { get; set; }
        public Nullable<int> nbr_children { get; set; }
        public string service_nationale { get; set; }
        public Nullable<System.DateTime> date_out_work { get; set; }
        public string etat_emply { get; set; }
        public int rotba_id_rotba { get; set; }
        public int branche_id_branche { get; set; }
        public bool date_n_bool { get; set; }
        public Nullable<int> date_n_prisime { get; set; }
        public string prenom_pere { get; set; }
        public int apc_annex_catgr_id_apc_annex { get; set; }
        public int apc_annex_catgr_detail_id_annex_detail { get; set; }
        public string diplome { get; set; }
        public int login_id_user { get; set; }
    
        public virtual ICollection<doc_vacance> doc_vacance { get; set; }
        public virtual ICollection<doc_promotion> doc_promotion { get; set; }
        public virtual ICollection<doc_ta9yim> doc_ta9yim { get; set; }
        public virtual ICollection<doc_displine> doc_displine { get; set; }
        public virtual ICollection<doc_7araka> doc_7araka { get; set; }
        public virtual ICollection<doc_vacane_plus> doc_vacane_plus { get; set; }
        public virtual ICollection<doc_morasalt_idariya> doc_morasalt_idariya { get; set; }
        public virtual ICollection<doc_mo7asaba> doc_mo7asaba { get; set; }
        public virtual rotba rotba { get; set; }
        public virtual branche branche { get; set; }
        public virtual ICollection<doc2_chngmnt_poste> doc2_chngmnt_poste { get; set; }
        public virtual ICollection<doc2_chngmt_daraja> doc2_chngmt_daraja { get; set; }
        public virtual ICollection<doc2_chngmnt_delgation> doc2_chngmnt_delgation { get; set; }
        public virtual ICollection<doc2_charge_poste> doc2_charge_poste { get; set; }
        public virtual apc_annex_catgr apc_annex_catgr { get; set; }
        public virtual apc_annex_catgr_detail apc_annex_catgr_detail { get; set; }
        public virtual login login { get; set; }
        public virtual ICollection<lieu_nominaiton> lieu_nominaiton { get; set; }
    }
}
