//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class lieu_nominaiton
    {
        public int id_lieu_nomination { get; set; }
        public System.DateTime date_change_lieu_nomination { get; set; }
        public int employ_id { get; set; }
        public int apc_annex_catgr_id_apc_annex { get; set; }
        public int apc_annex_catgr_detail_id_annex_detail { get; set; }
    
        public virtual employ employ { get; set; }
        public virtual apc_annex_catgr apc_annex_catgr { get; set; }
        public virtual apc_annex_catgr_detail apc_annex_catgr_detail { get; set; }
    }
}
