//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.employs = new HashSet<employ>();
        }
    
        public int id_user { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public int permision_login { get; set; }
    
        public virtual ICollection<employ> employs { get; set; }
    }
}
