//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employ> employSet { get; set; }
        public virtual DbSet<doc_vacance> doc_vacanceSet { get; set; }
        public virtual DbSet<rotba> rotbaSet { get; set; }
        public virtual DbSet<doc_promotion> doc_promotionSet { get; set; }
        public virtual DbSet<doc_ta9yim> doc_ta9yimSet { get; set; }
        public virtual DbSet<doc_mo7asaba> doc_mo7asabaSet { get; set; }
        public virtual DbSet<doc_7araka> doc_7arakaSet { get; set; }
        public virtual DbSet<doc_displine> doc_displineSet { get; set; }
        public virtual DbSet<doc_vacane_plus> doc_vacane_plusSet { get; set; }
        public virtual DbSet<doc_morasalt_idariya> doc_morasalt_idariyaSet { get; set; }
        public virtual DbSet<branche> brancheSet { get; set; }
        public virtual DbSet<doc2_chngmt_daraja> doc2_chngmt_darajaSet { get; set; }
        public virtual DbSet<doc2_chngmnt_delgation> doc2_chngmnt_delgationSet { get; set; }
        public virtual DbSet<doc2_chngmnt_poste> doc2_chngmnt_posteSet { get; set; }
        public virtual DbSet<doc2_charge_poste> doc2_charge_poste { get; set; }
        public virtual DbSet<apc_annex_catgr> apc_annex_catgr { get; set; }
        public virtual DbSet<apc_annex_catgr_detail> apc_annex_catgr_detail { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<lieu_nominaiton> lieu_nominaiton { get; set; }
    }
}
