//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apc.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class rotba
    {
        public rotba()
        {
            this.employ = new HashSet<employ>();
        }
    
        public int id_rotba { get; set; }
        public string nom_rotba { get; set; }
        public int sinf { get; set; }
        public int istidl { get; set; }
        public string silk { get; set; }
        public int branche_id_branche { get; set; }
    
        public virtual ICollection<employ> employ { get; set; }
        public virtual branche branche { get; set; }
    }
}
